### ISSUE TITLE
Creality_DWINTest - LCD Volume setting does not save

### ISSUE THREAD

**Issue by camprevail** [InsanityAutomation/Marlin#15]
For now I will just disconnect the speaker, lol

**Comment by InsanityAutomation** [comment]
Just to put the answer discussed elsewhere here as well, this is partly by design. The original code did unsafe eeprom writes on every volume adjustment. It was set to default language to English and volume to 50% in order to eliminate the constant and unsafe eeprom actions. Potentially as I look at merging some of this into the marlin 2.0 extui API, volume storage might come back but for the time being there isn't a simple safe solution to storing the last setpoint. You can however modify the default value when you flash to make it always start wherever you want!

**Comment by InsanityAutomation** [comment]
Note - Marlin 2.0 has had a wrapper for ExtUI eeprom settings so this may be feasible as I continue on that port.

**Comment by LMS0815** [comment]
Just the opposite question...
Is there any GCODE to trigger an alert signal after print is ready?
Would be nice to play the "start tune" on demand...
Could not find any...

**Comment by InsanityAutomation** [comment]
I can tie it to the buzzer at some point most likely. I might chase into it while im doing the rest of the eeprom stuff.

**Comment by LMS0815** [comment]
THX:
` M117 BUZZER `

**Comment by LMS0815** [comment]
Shouldn't M300 P0 disable volume?
http://marlinfw.org/docs/configuration/configuration.html#speaker

> The duration and frequency for the UI feedback sound. Set these to 0 to disable audio feedback in the LCD menus. Test audio output with the G-code M300 S880 P300

**Comment by InsanityAutomation** [comment]
Done, in next release.
