### ISSUE TITLE
Please provide UBL FW hex file versions as well

### ISSUE THREAD

**Issue by LMS0815** [InsanityAutomation/Marlin#71]
Please provide the ???_UBL_DW4.hex version as well.
_Especiallay CRX_BLTouch_DualFil_UBL_DW4.hex_
 THX!

**Comment by InsanityAutomation** [comment]
DW5 will get UBL back. It got dropped as one upstream patch was needed that I submitted the day after i published DW4, and the most common question I got was whats the difference between BIL and UBL. I have since gotten nearly as many asking for UBL back so it didnt help the number of questions! lol
